name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Se actualiza cada noche
  workflow_dispatch: # Permite actualizarlo manualmente
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Lufal-lab
          template: classic
          
          # Esto quita el encabezado con tu nombre y foto para que sea más limpio
          config_display: columns
          base: metadata
          base_hierarchical: yes
          
          # Configuramos la parte de Estadísticas (Izquierda)
          # Solo dejamos commits y repositorios para evitar los "0" en stars e issues
          base_common: yes
          base_header: no
          
          # Configuramos Lenguajes (Derecha)
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          
          # Ajustes visuales para que se parezca a tu imagen
          config_animations: yes
          config_timezone: America/Bogota
