name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Genera la tarjeta de Estadísticas (Izquierda)
      - uses: lowlighter/metrics@latest
        with:
          filename: stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: America/Bogota
          # Esto hace que se vea como una tarjeta compacta
          config_display: columns

      # Genera la tarjeta de Lenguajes (Derecha)
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8
